Add files via upload
coding steps :
1- add starting column (0) for each gene to "chromInfo.txt"
2- rename  "chromInfo.txt" to "genes.bed"
3- rename "dm3_exons.txt" to reads.bed"
2- from bedtools, I've run  the intersect command :
bedtools intersect -a reads.bed -b genes.bed > coding.bed


non coding steps:
1- create new genes file "genes_non.bed" to fit bedtools format., the new genes file contain only name of gene and end of gene.
2- run the complement command: 
bedtools complement -i coding.bed -g genes_non.bed > non-coding.bed

after running the complement command appear the following error:

Error: Sorted input specified, but the file coding.bed has the following out of order record
chr4	252055	252253	CG1674-RC_exon_0_0_chr4_252056_f	0	+

to solve this problem, I've sorted the "coding.bed" records using bedtools command:
sortBed -i coding.bed > sorted_coding.bed

as a result of sorting command we got new sorted file which is "sorted_coding.bed"

then, I've running the complement co